apiVersion: v1
kind: Service
metadata:
  name: speech-microservice-service
spec:
  selector:
    app: speech-microservice
  ports:
    - name: http
      port: 5007
      targetPort: 5007
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-microservice
  template:
    metadata:
      labels:
        app: speech-microservice
    spec:
      containers:
        - name: speech-service-container
          image: speech_microservice
          ports:
            - containerPort: 5007
          imagePullPolicy: Never